export type Category =
  | "All"
  | "📚 كتب مترجمة"
  | "🎓 كورسات"
  | "📐 قوالب"
  | "💻 برمجة"
  | "🎨 تصميم"
  | "💼 أعمال"
  | "🤖 ذكاء اصطناعي"
  | "📊 مالية";

export interface Product {
  id: number;
  title: string;
  titleAr: string;
  category: Category;
  price: number;
  pages: number;
  desc: string;
  badge?: "BESTSELLER" | "NEW" | "FREE" | "HOT" | "TOP";
  rating: number;
  downloads: number;
  image: string;
}

const IMGS = {
  books:     "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&auto=format&fit=crop&q=70",
  books2:    "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&auto=format&fit=crop&q=70",
  books3:    "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&auto=format&fit=crop&q=70",
  phil:      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=70",
  code:      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&auto=format&fit=crop&q=70",
  code2:     "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&auto=format&fit=crop&q=70",
  code3:     "https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=400&auto=format&fit=crop&q=70",
  design:    "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&auto=format&fit=crop&q=70",
  design2:   "https://images.unsplash.com/photo-1558655146-d09347e92766?w=400&auto=format&fit=crop&q=70",
  business:  "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&auto=format&fit=crop&q=70",
  business2: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&auto=format&fit=crop&q=70",
  finance:   "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&auto=format&fit=crop&q=70",
  finance2:  "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=400&auto=format&fit=crop&q=70",
  template:  "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&auto=format&fit=crop&q=70",
  template2: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&auto=format&fit=crop&q=70",
  marketing: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&auto=format&fit=crop&q=70",
  ai:        "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&auto=format&fit=crop&q=70",
  ai2:       "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&auto=format&fit=crop&q=70",
  science:   "https://images.unsplash.com/photo-1532094349884-543604242e35?w=400&auto=format&fit=crop&q=70",
  data:      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=70",
};

export const CATEGORIES: Category[] = [
  "All",
  "📚 كتب مترجمة",
  "🎓 كورسات",
  "📐 قوالب",
  "💻 برمجة",
  "🎨 تصميم",
  "💼 أعمال",
  "🤖 ذكاء اصطناعي",
  "📊 مالية",
];

export const products: Product[] = [

  // ─── 📚 كتب مترجمة (40 products) ───────────────────────────────────
  {
    id: 1, category: "📚 كتب مترجمة",
    title: "Meditations – Marcus Aurelius",
    titleAr: "تأملات – ماركوس أوريليوس",
    price: 25, pages: 254, rating: 4.9, downloads: 18420,
    badge: "BESTSELLER",
    desc: "الترجمة الكاملة لتأملات الإمبراطور الرواقي. فلسفة الانضباط والهدوء والفضيلة. إصدار ملون مع شروحات.",
    image: IMGS.phil,
  },
  {
    id: 2, category: "📚 كتب مترجمة",
    title: "The Art of War – Sun Tzu",
    titleAr: "فن الحرب – سون تزو",
    price: 20, pages: 112, rating: 4.8, downloads: 22100,
    badge: "TOP",
    desc: "الترجمة العربية الكاملة مع تعليقات معاصرة على كل مبدأ. مرجع الاستراتيجية الأبدي.",
    image: IMGS.books,
  },
  {
    id: 3, category: "📚 كتب مترجمة",
    title: "The Prince – Niccolò Machiavelli",
    titleAr: "الأمير – ميكافيلي",
    price: 22, pages: 186, rating: 4.7, downloads: 14300,
    desc: "الترجمة العربية الكاملة من النص الإيطالي الأصلي. كتاب السياسة والقوة الأكثر إثارة للجدل.",
    image: IMGS.books2,
  },
  {
    id: 4, category: "📚 كتب مترجمة",
    title: "The Republic – Plato",
    titleAr: "الجمهورية – أفلاطون",
    price: 30, pages: 342, rating: 4.8, downloads: 11200,
    desc: "أعظم حوارات أفلاطون السياسية والفلسفية. ترجمة أكاديمية مشروحة باللغة العربية.",
    image: IMGS.phil,
  },
  {
    id: 5, category: "📚 كتب مترجمة",
    title: "The Wealth of Nations – Adam Smith",
    titleAr: "ثروة الأمم – آدم سميث",
    price: 40, pages: 528, rating: 4.6, downloads: 8900,
    badge: "TOP",
    desc: "المختصر المترجم للأجزاء الجوهرية من أساس علم الاقتصاد الحديث. مفهرس بالمصطلحات.",
    image: IMGS.finance,
  },
  {
    id: 6, category: "📚 كتب مترجمة",
    title: "On the Origin of Species – Darwin",
    titleAr: "أصل الأنواع – داروين",
    price: 35, pages: 395, rating: 4.7, downloads: 9600,
    desc: "الترجمة الكاملة للطبعة السادسة. أهم كتاب في تاريخ العلوم الطبيعية مترجماً بدقة أكاديمية.",
    image: IMGS.science,
  },
  {
    id: 7, category: "📚 كتب مترجمة",
    title: "The Richest Man in Babylon",
    titleAr: "أغنى رجل في بابل",
    price: 28, pages: 158, rating: 4.9, downloads: 25800,
    badge: "BESTSELLER",
    desc: "قصص بابل الخالدة في مبادئ المال والثروة. ترجمة عربية كاملة مع رسوم توضيحية.",
    image: IMGS.finance2,
  },
  {
    id: 8, category: "📚 كتب مترجمة",
    title: "As a Man Thinketh – James Allen",
    titleAr: "كما يفكر الإنسان",
    price: 18, pages: 78, rating: 4.8, downloads: 19400,
    desc: "كتاب التفكير الإيجابي الكلاسيكي. قوة العقل في تشكيل الحياة. ترجمة موسعة مع تأملات.",
    image: IMGS.books3,
  },
  {
    id: 9, category: "📚 كتب مترجمة",
    title: "The Science of Getting Rich – Wattles",
    titleAr: "علم الثروة – واتلز",
    price: 22, pages: 142, rating: 4.7, downloads: 13700,
    desc: "1910 — مرجع قانون الجذب الأصلي. ترجمة عربية كاملة مع شرح الأفكار الرئيسية.",
    image: IMGS.finance,
  },
  {
    id: 10, category: "📚 كتب مترجمة",
    title: "Self-Reliance – Ralph Waldo Emerson",
    titleAr: "الاعتماد على الذات – إيمرسون",
    price: 20, pages: 96, rating: 4.6, downloads: 11100,
    desc: "مقالة الفيلسوف الأمريكي الكبرى في الاستقلالية والهوية الفردية. إصدار مشروح بالكامل.",
    image: IMGS.books,
  },
  {
    id: 11, category: "📚 كتب مترجمة",
    title: "Walden – Henry David Thoreau",
    titleAr: "والدن – ثورو",
    price: 30, pages: 312, rating: 4.5, downloads: 7800,
    desc: "تجربة العيش البسيط في الطبيعة والتأمل الفلسفي. ترجمة أدبية راقية مع مقدمة نقدية.",
    image: IMGS.books2,
  },
  {
    id: 12, category: "📚 كتب مترجمة",
    title: "Beyond Good and Evil – Nietzsche",
    titleAr: "ما وراء الخير والشر – نيتشه",
    price: 32, pages: 264, rating: 4.7, downloads: 12500,
    desc: "أحد أعمق مؤلفات نيتشه. ترجمة فلسفية دقيقة مع مسرد للمصطلحات الألمانية.",
    image: IMGS.phil,
  },
  {
    id: 13, category: "📚 كتب مترجمة",
    title: "Thus Spoke Zarathustra – Nietzsche",
    titleAr: "هكذا تكلم زرادشت – نيتشه",
    price: 35, pages: 288, rating: 4.8, downloads: 15200,
    badge: "HOT",
    desc: "الملحمة الفلسفية الكبرى لنيتشه. ترجمة شعرية محكمة توازي الأصل الألماني.",
    image: IMGS.phil,
  },
  {
    id: 14, category: "📚 كتب مترجمة",
    title: "The Interpretation of Dreams – Freud",
    titleAr: "تفسير الأحلام – فرويد",
    price: 38, pages: 456, rating: 4.6, downloads: 9200,
    desc: "العمل المؤسس لعلم النفس التحليلي. ترجمة أكاديمية كاملة للطبعة الألمانية الأصلية.",
    image: IMGS.books3,
  },
  {
    id: 15, category: "📚 كتب مترجمة",
    title: "Democracy in America – Tocqueville",
    titleAr: "الديمقراطية في أمريكا – توكفيل",
    price: 40, pages: 398, rating: 4.5, downloads: 6800,
    desc: "المختصر المترجم للمجلدين الكبيرين. رؤية الفيلسوف الفرنسي للتجربة الديمقراطية الأمريكية.",
    image: IMGS.books,
  },
  {
    id: 16, category: "📚 كتب مترجمة",
    title: "The Social Contract – Rousseau",
    titleAr: "العقد الاجتماعي – روسو",
    price: 25, pages: 218, rating: 4.7, downloads: 11800,
    desc: "أساس الفلسفة السياسية الحديثة. ترجمة علمية كاملة مع مقدمة تأريخية مفصلة.",
    image: IMGS.books2,
  },
  {
    id: 17, category: "📚 كتب مترجمة",
    title: "The Metamorphosis – Franz Kafka",
    titleAr: "المسخ – كافكا",
    price: 18, pages: 98, rating: 4.9, downloads: 20600,
    badge: "TOP",
    desc: "الرواية القصيرة الأكثر تأثيراً في القرن العشرين. ترجمة أدبية حرفية مع مقدمة نقدية.",
    image: IMGS.books3,
  },
  {
    id: 18, category: "📚 كتب مترجمة",
    title: "Siddhartha – Hermann Hesse",
    titleAr: "سيدهارتا – هيرمان هيسه",
    price: 26, pages: 172, rating: 4.8, downloads: 17300,
    desc: "رحلة روحية عبر الفلسفة البوذية والهندوسية. ترجمة عربية راقية للرواية الفلسفية الألمانية.",
    image: IMGS.books,
  },
  {
    id: 19, category: "📚 كتب مترجمة",
    title: "The Odyssey – Homer",
    titleAr: "الأوديسا – هوميروس",
    price: 32, pages: 368, rating: 4.8, downloads: 14900,
    desc: "ملحمة هوميروس الخالدة كاملة. ترجمة شعرية عربية مع ملاحظات جغرافية وأسطورية.",
    image: IMGS.books2,
  },
  {
    id: 20, category: "📚 كتب مترجمة",
    title: "The Iliad – Homer",
    titleAr: "الإلياذة – هوميروس",
    price: 34, pages: 412, rating: 4.7, downloads: 12800,
    desc: "الملحمة الحربية الأعظم في تاريخ البشرية. ترجمة عربية شعرية محكمة مع شرح الشخصيات.",
    image: IMGS.books3,
  },
  {
    id: 21, category: "📚 كتب مترجمة",
    title: "The Great Gatsby – F. Scott Fitzgerald",
    titleAr: "غاتسبي العظيم – فيتزجيرالد",
    price: 24, pages: 196, rating: 4.7, downloads: 19800,
    badge: "HOT",
    desc: "رمز الحلم الأمريكي وزيفه. ترجمة أدبية دقيقة مع دراسة نقدية وتحليل الشخصيات.",
    image: IMGS.books,
  },
  {
    id: 22, category: "📚 كتب مترجمة",
    title: "Crime and Punishment – Dostoevsky",
    titleAr: "الجريمة والعقاب – دوستويفسكي",
    price: 36, pages: 548, rating: 4.9, downloads: 16400,
    badge: "BESTSELLER",
    desc: "رواية الإنسانية الكبرى. ترجمة عربية كاملة ومدققة من الروسية الأصلية في مجلد واحد.",
    image: IMGS.books2,
  },
  {
    id: 23, category: "📚 كتب مترجمة",
    title: "The Brothers Karamazov – Dostoevsky",
    titleAr: "الإخوة كارامازوف – دوستويفسكي",
    price: 42, pages: 822, rating: 4.9, downloads: 13200,
    desc: "خلاصة إبداع دوستويفسكي الفلسفي والروائي. ترجمة أكاديمية عربية بمجلدين مدمجين.",
    image: IMGS.books3,
  },
  {
    id: 24, category: "📚 كتب مترجمة",
    title: "Don Quixote – Cervantes (Abridged)",
    titleAr: "دون كيخوتي – سيرفانتس (مختصر)",
    price: 30, pages: 320, rating: 4.6, downloads: 10400,
    desc: "المختصر العربي للرواية الأم في الأدب الغربي. ترجمة راقية تحافظ على روح الأصل.",
    image: IMGS.books,
  },
  {
    id: 25, category: "📚 كتب مترجمة",
    title: "Les Misérables – Victor Hugo (Abridged)",
    titleAr: "البؤساء – فيكتور هوغو (مختصر)",
    price: 38, pages: 480, rating: 4.8, downloads: 18700,
    desc: "الملحمة الإنسانية الكبرى في نسخة عربية مختصرة تحافظ على خط القصة الرئيسي.",
    image: IMGS.books2,
  },
  {
    id: 26, category: "📚 كتب مترجمة",
    title: "Two Treatises of Government – Locke",
    titleAr: "رسالتان في الحكومة – لوك",
    price: 28, pages: 286, rating: 4.5, downloads: 7200,
    desc: "أساس الليبرالية الكلاسيكية وحقوق الإنسان. ترجمة أكاديمية كاملة مع مسرد مصطلحات.",
    image: IMGS.books3,
  },
  {
    id: 27, category: "📚 كتب مترجمة",
    title: "Leviathan – Thomas Hobbes",
    titleAr: "لفياثان – توماس هوبز",
    price: 38, pages: 468, rating: 4.6, downloads: 6900,
    desc: "فلسفة الدولة والسلطة في الفكر السياسي الغربي. مختصر ومترجم من الإنجليزية القديمة.",
    image: IMGS.phil,
  },
  {
    id: 28, category: "📚 كتب مترجمة",
    title: "The Federalist Papers – Hamilton, Madison, Jay",
    titleAr: "أوراق الفيدراليست",
    price: 35, pages: 340, rating: 4.6, downloads: 8100,
    desc: "85 مقالة أسست الدستور الأمريكي. اختيار وترجمة المقالات الأهم مع شروحات سياسية.",
    image: IMGS.books,
  },
  {
    id: 29, category: "📚 كتب مترجمة",
    title: "The Adventures of Tom Sawyer – Twain",
    titleAr: "مغامرات توم سوير – مارك توين",
    price: 22, pages: 248, rating: 4.7, downloads: 14600,
    desc: "الرواية الكلاسيكية الممتعة لمارك توين. ترجمة عربية راقية محببة للكبار والصغار.",
    image: IMGS.books2,
  },
  {
    id: 30, category: "📚 كتب مترجمة",
    title: "The Power of Concentration – Dumont",
    titleAr: "قوة التركيز – دومونت",
    price: 20, pages: 132, rating: 4.6, downloads: 11900,
    desc: "1918 — دليل تقنيات التركيز الذهني وتنمية الإرادة. ترجمة عربية مع تطبيقات عملية.",
    image: IMGS.books3,
  },
  {
    id: 31, category: "📚 كتب مترجمة",
    title: "Anna Karenina – Tolstoy (Abridged)",
    titleAr: "آنا كارينينا – تولستوي (مختصر)",
    price: 35, pages: 420, rating: 4.8, downloads: 15800,
    badge: "HOT",
    desc: "درة الأدب الروسي. مختصر عربي يحافظ على الخطوط الدرامية والنفسية الكبرى للرواية.",
    image: IMGS.books,
  },
  {
    id: 32, category: "📚 كتب مترجمة",
    title: "Common Sense – Thomas Paine",
    titleAr: "الحس السليم – توماس بين",
    price: 18, pages: 96, rating: 4.7, downloads: 12400,
    desc: "الكتيّب الذي أشعل الثورة الأمريكية 1776. ترجمة عربية كاملة مع سياق تاريخي.",
    image: IMGS.books2,
  },
  {
    id: 33, category: "📚 كتب مترجمة",
    title: "Ulysses – James Joyce (Modern Edition)",
    titleAr: "يوليسيس – جيمس جويس (طبعة معاصرة)",
    price: 45, pages: 280, rating: 4.4, downloads: 5600,
    desc: "مختصر مترجم للرواية الأصعب في تاريخ الأدب مع دليل فهم وخريطة الأحداث.",
    image: IMGS.books3,
  },
  {
    id: 34, category: "📚 كتب مترجمة",
    title: "Critique of Pure Reason – Kant (Summary)",
    titleAr: "نقد العقل المحض – كانط (مختصر)",
    price: 32, pages: 198, rating: 4.5, downloads: 7400,
    desc: "ملخص أكاديمي معمق لأصعب كتاب فلسفي. مترجم مع أمثلة معاصرة تشرح الأفكار الكانطية.",
    image: IMGS.phil,
  },
  {
    id: 35, category: "📚 كتب مترجمة",
    title: "The Communist Manifesto – Marx & Engels",
    titleAr: "البيان الشيوعي – ماركس وإنجلز",
    price: 18, pages: 88, rating: 4.6, downloads: 16200,
    desc: "أحد أكثر الوثائق السياسية تأثيراً. ترجمة عربية نقدية كاملة مع مقدمة تاريخية.",
    image: IMGS.books,
  },
  {
    id: 36, category: "📚 كتب مترجمة",
    title: "A Room with a View – E.M. Forster",
    titleAr: "غرفة ذات منظر – فورستر",
    price: 22, pages: 198, rating: 4.5, downloads: 8900,
    desc: "رواية اجتماعية راقية من إدوارد فورستر. ترجمة أدبية بالكامل مع ملاحظات ثقافية.",
    image: IMGS.books2,
  },
  {
    id: 37, category: "📚 كتب مترجمة",
    title: "Das Kapital Vol. 1 – Karl Marx (Summary)",
    titleAr: "رأس المال ج١ – كارل ماركس (مختصر)",
    price: 38, pages: 248, rating: 4.6, downloads: 9800,
    desc: "ملخص منهجي للجزء الأول من رأس المال. يشرح نظرية القيمة والفائض بلغة عربية ميسرة.",
    image: IMGS.books3,
  },
  {
    id: 38, category: "📚 كتب مترجمة",
    title: "The General Theory of Employment – Keynes",
    titleAr: "النظرية العامة للتوظيف – كينز",
    price: 42, pages: 312, rating: 4.5, downloads: 6700,
    desc: "مختصر ومترجم للعمل الاقتصادي الذي غيّر الاقتصاد العالمي. مع شروحات معاصرة.",
    image: IMGS.finance,
  },
  {
    id: 39, category: "📚 كتب مترجمة",
    title: "The Jungle Book – Rudyard Kipling",
    titleAr: "كتاب الأدغال – كيبلينج",
    price: 20, pages: 218, rating: 4.7, downloads: 13400,
    desc: "القصص الأصلية الكاملة لكتاب الأدغال. ترجمة عربية محببة للكبار والأطفال بإصدار مصوّر.",
    image: IMGS.books,
  },
  {
    id: 40, category: "📚 كتب مترجمة",
    title: "Huckleberry Finn – Mark Twain",
    titleAr: "هاكلبيري فين – مارك توين",
    price: 24, pages: 312, rating: 4.7, downloads: 12900,
    desc: "مغامرة الهروب على نهر المسيسيبي. ترجمة عربية كاملة لأشهر روايات مارك توين.",
    image: IMGS.books2,
  },

  // ─── 🎓 كورسات (30 products) ────────────────────────────────────────
  {
    id: 41, category: "🎓 كورسات",
    title: "Python for Beginners – Complete PDF Course",
    titleAr: "بايثون للمبتدئين – كورس PDF كامل",
    price: 120, pages: 486, rating: 4.9, downloads: 31200,
    badge: "BESTSELLER",
    desc: "من الصفر إلى متقدم. شرح تفاعلي كامل مع تمارين محلولة وأكثر من 100 مثال عملي.",
    image: IMGS.code,
  },
  {
    id: 42, category: "🎓 كورسات",
    title: "Web Development Fundamentals – HTML CSS JS",
    titleAr: "أساسيات تطوير الويب – HTML CSS JS",
    price: 150, pages: 612, rating: 4.8, downloads: 26800,
    badge: "HOT",
    desc: "دليل شامل يغطي HTML5 وCSS3 وJavaScript الحديث من الصفر. 80+ مشروع عملي.",
    image: IMGS.code2,
  },
  {
    id: 43, category: "🎓 كورسات",
    title: "Introduction to Machine Learning – PDF Guide",
    titleAr: "مقدمة في تعلم الآلة – دليل PDF",
    price: 200, pages: 554, rating: 4.8, downloads: 19600,
    desc: "الأسس الرياضية والعملية لتعلم الآلة. يشمل الخوارزميات الأساسية مع Python وScikit-learn.",
    image: IMGS.ai,
  },
  {
    id: 44, category: "🎓 كورسات",
    title: "Data Science with Python – Full Course",
    titleAr: "علم البيانات مع بايثون – كورس كامل",
    price: 220, pages: 638, rating: 4.9, downloads: 22400,
    badge: "BESTSELLER",
    desc: "pandas, numpy, matplotlib, seaborn وسكيكيت-ليرن كلها في دليل واحد شامل ومنظم.",
    image: IMGS.data,
  },
  {
    id: 45, category: "🎓 كورسات",
    title: "Git & GitHub – Complete Mastery Guide",
    titleAr: "Git و GitHub – دليل الإتقان الكامل",
    price: 80, pages: 284, rating: 4.8, downloads: 28900,
    desc: "كل ما تحتاجه لإتقان Git: branching, merging, rebasing, PRs, CI/CD. مع أمثلة واقعية.",
    image: IMGS.code3,
  },
  {
    id: 46, category: "🎓 كورسات",
    title: "Linux Command Line Mastery",
    titleAr: "إتقان سطر أوامر لينكس",
    price: 90, pages: 318, rating: 4.8, downloads: 21700,
    desc: "من المستخدم المبتدئ إلى مسؤول الأنظمة. يشمل Shell Scripting, Cron, Networking.",
    image: IMGS.code,
  },
  {
    id: 47, category: "🎓 كورسات",
    title: "JavaScript ES6+ Modern Guide",
    titleAr: "دليل JavaScript الحديث ES6+",
    price: 130, pages: 428, rating: 4.8, downloads: 25300,
    badge: "HOT",
    desc: "Arrow functions, Promises, async/await, Modules, Destructuring وكل ميزات JS الحديثة.",
    image: IMGS.code2,
  },
  {
    id: 48, category: "🎓 كورسات",
    title: "React.js – Zero to Hero Complete Course",
    titleAr: "React.js – من الصفر إلى الاحتراف",
    price: 180, pages: 512, rating: 4.9, downloads: 29600,
    badge: "BESTSELLER",
    desc: "Hooks, Context, React Router, Redux, Testing وبناء 3 مشاريع كاملة من الصفر.",
    image: IMGS.code3,
  },
  {
    id: 49, category: "🎓 كورسات",
    title: "SQL Database Design Masterclass",
    titleAr: "ماستركلاس تصميم قواعد بيانات SQL",
    price: 140, pages: 396, rating: 4.7, downloads: 16800,
    desc: "تصميم الجداول، العلاقات، الـ Normalization، الـ Queries المتقدمة، وتحسين الأداء.",
    image: IMGS.data,
  },
  {
    id: 50, category: "🎓 كورسات",
    title: "Cybersecurity Fundamentals – Complete PDF",
    titleAr: "أساسيات الأمن السيبراني – PDF كامل",
    price: 160, pages: 458, rating: 4.8, downloads: 18200,
    desc: "Network security, Ethical hacking basics, OWASP Top 10, Cryptography وممارسات الحماية.",
    image: IMGS.code,
  },
  {
    id: 51, category: "🎓 كورسات",
    title: "Docker & Containerization Complete Guide",
    titleAr: "Docker والـ Containerization – الدليل الكامل",
    price: 130, pages: 342, rating: 4.7, downloads: 14600,
    desc: "Containers, Images, Compose, Volumes, Networking, ونشر التطبيقات في الإنتاج.",
    image: IMGS.code2,
  },
  {
    id: 52, category: "🎓 كورسات",
    title: "UI/UX Design Fundamentals Course",
    titleAr: "أساسيات تصميم UI/UX – كورس كامل",
    price: 170, pages: 498, rating: 4.8, downloads: 22800,
    badge: "HOT",
    desc: "مبادئ التصميم، User Research, Wireframing, Prototyping وبناء Portfolio احترافي.",
    image: IMGS.design,
  },
  {
    id: 53, category: "🎓 كورسات",
    title: "Digital Marketing Strategy – A to Z",
    titleAr: "استراتيجية التسويق الرقمي – من الألف للياء",
    price: 150, pages: 412, rating: 4.7, downloads: 19400,
    desc: "SEO, SEM, Social Media, Email Marketing, Content Strategy وتحليل البيانات.",
    image: IMGS.marketing,
  },
  {
    id: 54, category: "🎓 كورسات",
    title: "SEO Complete Guide 2024 Edition",
    titleAr: "الدليل الكامل للـ SEO – إصدار 2024",
    price: 120, pages: 368, rating: 4.8, downloads: 24600,
    desc: "On-page, Off-page, Technical SEO, Core Web Vitals, Link Building وأدوات التحليل.",
    image: IMGS.marketing,
  },
  {
    id: 55, category: "🎓 كورسات",
    title: "Entrepreneurship 101 – Complete Handbook",
    titleAr: "ريادة الأعمال 101 – الدليل الكامل",
    price: 140, pages: 384, rating: 4.7, downloads: 17200,
    desc: "من الفكرة إلى المنتج إلى الإيرادات. خطوات عملية لإطلاق مشروعك الأول بأقل موارد.",
    image: IMGS.business,
  },
  {
    id: 56, category: "🎓 كورسات",
    title: "Financial Literacy – Complete Course PDF",
    titleAr: "الثقافة المالية – كورس PDF كامل",
    price: 100, pages: 312, rating: 4.8, downloads: 21300,
    desc: "إدارة الميزانية، بناء الثروة، الاستثمار الذكي، والتخطيط المالي للمستقبل.",
    image: IMGS.finance,
  },
  {
    id: 57, category: "🎓 كورسات",
    title: "Investing for Beginners – Step by Step",
    titleAr: "الاستثمار للمبتدئين – خطوة بخطوة",
    price: 110, pages: 286, rating: 4.8, downloads: 23800,
    badge: "HOT",
    desc: "الأسهم، السندات، الصناديق، العقارات، والذهب. كيف تبني محفظة متنوعة من الصفر.",
    image: IMGS.finance2,
  },
  {
    id: 58, category: "🎓 كورسات",
    title: "Cryptocurrency & Blockchain – Full Guide",
    titleAr: "العملات الرقمية والبلوكتشين – دليل كامل",
    price: 160, pages: 398, rating: 4.7, downloads: 27400,
    desc: "كيف يعمل البلوكتشين، DeFi، التداول، المحافظ، والأمان. مع تحليل أهم العملات.",
    image: IMGS.finance,
  },
  {
    id: 59, category: "🎓 كورسات",
    title: "Public Speaking Mastery – PDF Guide",
    titleAr: "إتقان فن الخطابة – دليل PDF",
    price: 90, pages: 268, rating: 4.7, downloads: 14800,
    desc: "بناء الثقة، هيكل الخطاب، لغة الجسد، والتعامل مع الجمهور الصعب. تمارين عملية.",
    image: IMGS.business,
  },
  {
    id: 60, category: "🎓 كورسات",
    title: "Productivity & Time Management Course",
    titleAr: "الإنتاجية وإدارة الوقت – كورس كامل",
    price: 95, pages: 298, rating: 4.8, downloads: 25600,
    badge: "BESTSELLER",
    desc: "GTD، Pomodoro، Time Blocking، Deep Work وإدارة الطاقة. حوّل يومك بالكامل.",
    image: IMGS.business2,
  },
  {
    id: 61, category: "🎓 كورسات",
    title: "Copywriting Fundamentals – Complete Course",
    titleAr: "أساسيات كتابة النصوص التسويقية",
    price: 115, pages: 342, rating: 4.7, downloads: 16900,
    desc: "AIDA، قواعد الإقناع، كتابة الإعلانات، صفحات الهبوط، والبريد الإلكتروني التسويقي.",
    image: IMGS.marketing,
  },
  {
    id: 62, category: "🎓 كورسات",
    title: "Speed Reading Techniques – Full Course",
    titleAr: "تقنيات القراءة السريعة – كورس كامل",
    price: 75, pages: 198, rating: 4.6, downloads: 18400,
    desc: "ضاعف سرعة قراءتك 3 مرات مع الحفاظ على الاستيعاب. تمارين يومية تدريجية.",
    image: IMGS.books,
  },
  {
    id: 63, category: "🎓 كورسات",
    title: "Memory Improvement – Scientific Techniques",
    titleAr: "تحسين الذاكرة – تقنيات علمية",
    price: 85, pages: 224, rating: 4.7, downloads: 19200,
    desc: "قصر الذاكرة، Mind Mapping، Spaced Repetition وتقنيات الحفظ المستخدمة في بطولات عالمية.",
    image: IMGS.books3,
  },
  {
    id: 64, category: "🎓 كورسات",
    title: "Nutrition & Health Science – Full Guide",
    titleAr: "علم التغذية والصحة – الدليل الكامل",
    price: 100, pages: 356, rating: 4.7, downloads: 20800,
    desc: "الكيمياء الغذائية، بناء العضلات، الحمية الصحية والمكملات الغذائية. مستند علمياً.",
    image: IMGS.science,
  },
  {
    id: 65, category: "🎓 كورسات",
    title: "Email Marketing Handbook – Complete Guide",
    titleAr: "دليل التسويق بالبريد الإلكتروني الكامل",
    price: 90, pages: 268, rating: 4.7, downloads: 14600,
    desc: "بناء القائمة، كتابة Subject Lines مغرية، Automation Sequences ومعدلات الفتح.",
    image: IMGS.marketing,
  },
  {
    id: 66, category: "🎓 كورسات",
    title: "Social Media Marketing Mastery",
    titleAr: "إتقان التسويق عبر السوشيال ميديا",
    price: 130, pages: 386, rating: 4.8, downloads: 23600,
    badge: "HOT",
    desc: "Instagram, TikTok, LinkedIn, X. إنشاء المحتوى، الخوارزميات، النمو المدفوع والعضوي.",
    image: IMGS.marketing,
  },
  {
    id: 67, category: "🎓 كورسات",
    title: "Mindfulness & Meditation – Scientific Guide",
    titleAr: "اليقظة والتأمل – دليل علمي",
    price: 70, pages: 212, rating: 4.8, downloads: 22400,
    desc: "الدراسات العلمية، تقنيات التأمل، تمارين التنفس وبناء ممارسة يومية مستدامة.",
    image: IMGS.books,
  },
  {
    id: 68, category: "🎓 كورسات",
    title: "Business Plan Writing – Step by Step",
    titleAr: "كتابة خطة العمل – خطوة بخطوة",
    price: 80, pages: 234, rating: 4.7, downloads: 16800,
    desc: "هيكل الخطة، تحليل السوق، النماذج المالية وكيفية الحصول على تمويل من المستثمرين.",
    image: IMGS.business,
  },
  {
    id: 69, category: "🎓 كورسات",
    title: "Content Marketing Blueprint – 2024",
    titleAr: "مخطط تسويق المحتوى – 2024",
    price: 110, pages: 318, rating: 4.7, downloads: 17200,
    desc: "استراتيجية المحتوى، إنشاء Pillar Pages، Content Calendar وقياس العائد على الاستثمار.",
    image: IMGS.marketing,
  },
  {
    id: 70, category: "🎓 كورسات",
    title: "Leadership Development – Complete Course",
    titleAr: "تطوير القيادة – كورس كامل",
    price: 140, pages: 376, rating: 4.8, downloads: 18600,
    desc: "أنماط القيادة، بناء الفرق، إدارة الصراعات، وتحفيز الأداء العالي. مع دراسات حالة.",
    image: IMGS.business2,
  },

  // ─── 📐 قوالب (30 products) ─────────────────────────────────────────
  {
    id: 71, category: "📐 قوالب",
    title: "Professional Business Plan Template",
    titleAr: "قالب خطة عمل احترافي",
    price: 45, pages: 48, rating: 4.8, downloads: 22600,
    badge: "BESTSELLER",
    desc: "قالب Word + PDF كامل لخطة عمل شاملة. يشمل التحليل المالي، السوقي والتشغيلي.",
    image: IMGS.template,
  },
  {
    id: 72, category: "📐 قوالب",
    title: "Startup Pitch Deck Template – 20 Slides",
    titleAr: "قالب العرض التقديمي للناشئة – 20 شريحة",
    price: 55, pages: 20, rating: 4.9, downloads: 31800,
    badge: "HOT",
    desc: "تصميم احترافي يُقنع المستثمرين. يشمل Problem, Solution, Market, Traction وFinancials.",
    image: IMGS.template2,
  },
  {
    id: 73, category: "📐 قوالب",
    title: "Social Media Content Calendar – 365 Days",
    titleAr: "تقويم محتوى السوشيال ميديا – 365 يوم",
    price: 35, pages: 62, rating: 4.7, downloads: 28400,
    desc: "Excel + PDF. جدول محتوى سنوي كامل مع أفكار منشورات، مناسبات وأوقات النشر المثالية.",
    image: IMGS.template,
  },
  {
    id: 74, category: "📐 قوالب",
    title: "Financial Model Template – Excel + PDF",
    titleAr: "قالب النموذج المالي – Excel + PDF",
    price: 65, pages: 54, rating: 4.8, downloads: 17400,
    desc: "P&L, Balance Sheet, Cash Flow, Cap Table ونموذج الـ 3 بيانات المالية المترابطة.",
    image: IMGS.finance2,
  },
  {
    id: 75, category: "📐 قوالب",
    title: "Resume & CV Template Pack – 15 Designs",
    titleAr: "حزمة قوالب السيرة الذاتية – 15 تصميم",
    price: 30, pages: 30, rating: 4.9, downloads: 42800,
    badge: "BESTSELLER",
    desc: "15 تصميم عصري ومحترف قابل للتخصيص. يشمل نسخ ATS-Friendly لاجتياز فرز الـ HR.",
    image: IMGS.template2,
  },
  {
    id: 76, category: "📐 قوالب",
    title: "Project Management Template Pack",
    titleAr: "حزمة قوالب إدارة المشاريع",
    price: 40, pages: 58, rating: 4.7, downloads: 19600,
    desc: "Gantt Chart, Risk Matrix, RACI Chart, Project Charter وWeekly Status Report.",
    image: IMGS.template,
  },
  {
    id: 77, category: "📐 قوالب",
    title: "Invoice & Contract Template Pack",
    titleAr: "حزمة قوالب الفاتورة والعقد",
    price: 35, pages: 42, rating: 4.8, downloads: 24200,
    desc: "فاتورة احترافية، عقد خدمات، عقد فريلانس وعرض سعر. جاهزة للطباعة والإرسال.",
    image: IMGS.business,
  },
  {
    id: 78, category: "📐 قوالب",
    title: "Notion Productivity OS – Full System",
    titleAr: "نوشن – نظام إنتاجية كامل",
    price: 50, pages: 38, rating: 4.9, downloads: 35200,
    badge: "BESTSELLER",
    desc: "نظام حياة كامل في Notion: Tasks، Goals، Journal، Reading List، Finance Tracker.",
    image: IMGS.template2,
  },
  {
    id: 79, category: "📐 قوالب",
    title: "Brand Identity Guideline Template",
    titleAr: "قالب دليل الهوية البصرية للعلامة",
    price: 45, pages: 44, rating: 4.8, downloads: 18800,
    desc: "Logo usage, Color palette, Typography, Photography style وBrand Voice. 44 صفحة.",
    image: IMGS.design,
  },
  {
    id: 80, category: "📐 قوالب",
    title: "Sales Proposal Template – Winning Format",
    titleAr: "قالب عرض المبيعات – التنسيق الرابح",
    price: 38, pages: 34, rating: 4.7, downloads: 16400,
    desc: "الهيكل الذي يحوّل 70% من العروض إلى عقود. مع صفحة التسعير وشهادات العملاء.",
    image: IMGS.business2,
  },
  {
    id: 81, category: "📐 قوالب",
    title: "Annual Report Template – Corporate",
    titleAr: "قالب التقرير السنوي – شركات",
    price: 60, pages: 52, rating: 4.6, downloads: 11200,
    desc: "تصميم احترافي يشمل ملخص المدير التنفيذي، النتائج المالية والإنجازات بأناقة.",
    image: IMGS.template,
  },
  {
    id: 82, category: "📐 قوالب",
    title: "Marketing Plan Template – Full Year",
    titleAr: "قالب خطة التسويق – سنة كاملة",
    price: 42, pages: 56, rating: 4.7, downloads: 19800,
    desc: "SWOT Analysis, Customer Personas, Channel Strategy, Budget Allocation وKPIs.",
    image: IMGS.marketing,
  },
  {
    id: 83, category: "📐 قوالب",
    title: "Budget Planning Template – Personal & Business",
    titleAr: "قالب التخطيط للميزانية – شخصي وتجاري",
    price: 28, pages: 32, rating: 4.8, downloads: 29400,
    desc: "تتبع الإيرادات والمصروفات، خطط الادخار والديون. سهل الاستخدام بدون محاسب.",
    image: IMGS.finance,
  },
  {
    id: 84, category: "📐 قوالب",
    title: "Employee Handbook Template",
    titleAr: "قالب دليل الموظف",
    price: 50, pages: 68, rating: 4.6, downloads: 13600,
    desc: "سياسات الشركة، الحقوق والواجبات، إجراءات الشكاوى وبيئة العمل الاحترافية.",
    image: IMGS.business,
  },
  {
    id: 85, category: "📐 قوالب",
    title: "YouTube Thumbnail Template Pack – 100 Designs",
    titleAr: "حزمة قوالب YouTube Thumbnail – 100 تصميم",
    price: 40, pages: 100, rating: 4.9, downloads: 38600,
    badge: "HOT",
    desc: "100 تصميم مخصص للـ CTR العالي. مصنفة حسب النيش: تعليم، ترفيه، تقنية وأعمال.",
    image: IMGS.design2,
  },
  {
    id: 86, category: "📐 قوالب",
    title: "Instagram Story Templates – 200 Pack",
    titleAr: "قوالب Instagram Stories – 200 تصميم",
    price: 35, pages: 200, rating: 4.8, downloads: 44200,
    badge: "BESTSELLER",
    desc: "200 قالب Story عصري. أنيميشن جاهز، ألوان قابلة للتخصيص، مناسب لكل النيش.",
    image: IMGS.design,
  },
  {
    id: 87, category: "📐 قوالب",
    title: "Presentation Template Pack – 5 Themes",
    titleAr: "حزمة قوالب العرض التقديمي – 5 ثيمات",
    price: 45, pages: 150, rating: 4.7, downloads: 21800,
    desc: "5 ثيمات احترافية: Corporate, Minimal, Creative, Tech وDark. 30 شريحة لكل ثيم.",
    image: IMGS.template2,
  },
  {
    id: 88, category: "📐 قوالب",
    title: "Legal Contract Templates Pack – 12 Types",
    titleAr: "حزمة العقود القانونية – 12 نوع",
    price: 55, pages: 96, rating: 4.7, downloads: 15800,
    desc: "NDA, Freelance Agreement, SLA, Partnership Agreement وعقود الخدمات الأساسية.",
    image: IMGS.business2,
  },
  {
    id: 89, category: "📐 قوالب",
    title: "OKR Goal Setting Template",
    titleAr: "قالب تحديد الأهداف OKR",
    price: 30, pages: 28, rating: 4.8, downloads: 22400,
    desc: "قالب OKR يستخدمه Google وIntel. يشمل تتبع ربعي، مراجعات أسبوعية ومسرد مفاهيم.",
    image: IMGS.template,
  },
  {
    id: 90, category: "📐 قوالب",
    title: "E-commerce Product Page Template Kit",
    titleAr: "مجموعة قوالب صفحة المنتج",
    price: 48, pages: 36, rating: 4.7, downloads: 14200,
    desc: "قوالب صفحات المنتج الأكثر تحويلاً. تشمل wireframes وCopy Framework للوصف.",
    image: IMGS.design2,
  },
  {
    id: 91, category: "📐 قوالب",
    title: "Press Release Template – PR Kit",
    titleAr: "قالب البيان الصحفي – مجموعة PR",
    price: 32, pages: 24, rating: 4.6, downloads: 11800,
    desc: "هيكل البيان الصحفي المقبول في وسائل الإعلام. 3 أنواع: إطلاق، شراكة وجائزة.",
    image: IMGS.template2,
  },
  {
    id: 92, category: "📐 قوالب",
    title: "SWOT & Market Analysis Template",
    titleAr: "قالب تحليل SWOT والسوق",
    price: 28, pages: 32, rating: 4.7, downloads: 17600,
    desc: "تحليل SWOT، Porter's 5 Forces، Competitive Matrix وCustomer Persona. مع تعليمات.",
    image: IMGS.business,
  },
  {
    id: 93, category: "📐 قوالب",
    title: "Product Roadmap Template",
    titleAr: "قالب خارطة طريق المنتج",
    price: 38, pages: 26, rating: 4.7, downloads: 14800,
    desc: "خارطة طريق بصرية للمنتج. تشمل Quarterly Planning, Feature Prioritization وRelease Plans.",
    image: IMGS.template,
  },
  {
    id: 94, category: "📐 قوالب",
    title: "Grant Proposal Template – Nonprofit",
    titleAr: "قالب طلب المنحة – للمنظمات غير الربحية",
    price: 40, pages: 42, rating: 4.6, downloads: 9800,
    desc: "هيكل طلب المنح الذي يزيد معدل القبول بنسبة 40%. مع أمثلة من منح مقبولة فعلاً.",
    image: IMGS.business2,
  },
  {
    id: 95, category: "📐 قوالب",
    title: "Customer Journey Map Template",
    titleAr: "قالب خريطة رحلة العميل",
    price: 35, pages: 22, rating: 4.8, downloads: 16400,
    desc: "تصور تجربة العميل في كل مرحلة. Touchpoints، Pain Points وفرص التحسين.",
    image: IMGS.design,
  },
  {
    id: 96, category: "📐 قوالب",
    title: "UX Research Template Kit",
    titleAr: "مجموعة قوالب أبحاث تجربة المستخدم",
    price: 42, pages: 46, rating: 4.7, downloads: 13200,
    desc: "User Interview Guide, Survey Template, Usability Test Script وAffinity Diagram.",
    image: IMGS.design2,
  },
  {
    id: 97, category: "📐 قوالب",
    title: "Meeting Agenda & Minutes Templates",
    titleAr: "قوالب أجندة الاجتماعات ومحاضرها",
    price: 22, pages: 20, rating: 4.7, downloads: 21200,
    desc: "5 قوالب: Stand-up, Strategy Meeting, Client Call, Board Meeting وBrainstorm.",
    image: IMGS.template2,
  },
  {
    id: 98, category: "📐 قوالب",
    title: "Landing Page Copy Template – High Converting",
    titleAr: "قالب نصوص صفحة الهبوط – عالي التحويل",
    price: 38, pages: 30, rating: 4.8, downloads: 19800,
    desc: "Hero, Features, Social Proof, FAQ وCTA sections. نصوص جاهزة قابلة للتخصيص.",
    image: IMGS.marketing,
  },
  {
    id: 99, category: "📐 قوالب",
    title: "Content Strategy Template – Editorial",
    titleAr: "قالب استراتيجية المحتوى التحريري",
    price: 36, pages: 34, rating: 4.7, downloads: 15600,
    desc: "Audience Matrix, Pillar Content Plan, Distribution Calendar وPerformance Tracker.",
    image: IMGS.template,
  },
  {
    id: 100, category: "📐 قوالب",
    title: "Email Newsletter Template Pack – 20 Designs",
    titleAr: "حزمة قوالب البريد الإلكتروني – 20 تصميم",
    price: 32, pages: 40, rating: 4.8, downloads: 23400,
    desc: "20 تصميم HTML+PDF لـ Newsletters. تغطي: Welcome, Weekly Digest, Promotion وEvent.",
    image: IMGS.marketing,
  },

  // ─── 💻 برمجة (20 products) ─────────────────────────────────────────
  {
    id: 101, category: "💻 برمجة",
    title: "System Design Interview Handbook",
    titleAr: "دليل مقابلات تصميم الأنظمة",
    price: 180, pages: 498, rating: 4.9, downloads: 28600,
    badge: "BESTSELLER",
    desc: "FAANG-level system design: Load Balancing, Caching, Databases, Microservices ومخططات.",
    image: IMGS.code,
  },
  {
    id: 102, category: "💻 برمجة",
    title: "Data Structures & Algorithms – Complete Guide",
    titleAr: "هياكل البيانات والخوارزميات – الدليل الكامل",
    price: 160, pages: 512, rating: 4.9, downloads: 24800,
    badge: "HOT",
    desc: "Arrays, Trees, Graphs, Sorting, Dynamic Programming. أكثر من 150 مسألة محلولة.",
    image: IMGS.code2,
  },
  {
    id: 103, category: "💻 برمجة",
    title: "REST API Design Principles & Best Practices",
    titleAr: "مبادئ تصميم REST API",
    price: 100, pages: 286, rating: 4.8, downloads: 18400,
    desc: "Versioning, Authentication, Rate Limiting, Error Handling والتوثيق باستخدام OpenAPI.",
    image: IMGS.code3,
  },
  {
    id: 104, category: "💻 برمجة",
    title: "The Complete SQL Reference Guide",
    titleAr: "المرجع الكامل لـ SQL",
    price: 90, pages: 342, rating: 4.8, downloads: 22600,
    desc: "من SELECT إلى Window Functions والـ CTEs المعقدة. مع 200 مثال على قواعد بيانات حقيقية.",
    image: IMGS.data,
  },
  {
    id: 105, category: "💻 برمجة",
    title: "Web Performance Optimization – Complete Guide",
    titleAr: "دليل تحسين أداء الويب الكامل",
    price: 110, pages: 318, rating: 4.7, downloads: 14800,
    desc: "Core Web Vitals, Lazy Loading, Code Splitting, CDN, وCaching Strategies. قياسات حقيقية.",
    image: IMGS.code,
  },
  {
    id: 106, category: "💻 برمجة",
    title: "GitHub Actions CI/CD Complete Guide",
    titleAr: "دليل GitHub Actions و CI/CD الكامل",
    price: 120, pages: 298, rating: 4.8, downloads: 16200,
    desc: "بناء Pipelines كاملة: Test, Build, Deploy, Rollback مع استراتيجيات Kubernetes.",
    image: IMGS.code2,
  },
  {
    id: 107, category: "💻 برمجة",
    title: "The Complete Networking Guide for Developers",
    titleAr: "دليل الشبكات الكامل للمطورين",
    price: 95, pages: 346, rating: 4.7, downloads: 13400,
    desc: "TCP/IP, DNS, HTTP/2, WebSockets, VPN وFirewalls. كل ما يحتاجه المطور لفهم الشبكات.",
    image: IMGS.code3,
  },
  {
    id: 108, category: "💻 برمجة",
    title: "Linux SysAdmin Handbook – Complete Reference",
    titleAr: "دليل مسؤول نظام Linux الكامل",
    price: 130, pages: 486, rating: 4.8, downloads: 17800,
    badge: "HOT",
    desc: "Process Management, File Systems, Security, Monitoring وAutomation. أكثر من 400 أمر.",
    image: IMGS.code,
  },
  {
    id: 109, category: "💻 برمجة",
    title: "API Security – Complete Developer Guide",
    titleAr: "أمان API – الدليل الكامل للمطور",
    price: 115, pages: 312, rating: 4.8, downloads: 14600,
    desc: "OWASP API Top 10, JWT, OAuth 2.0, Rate Limiting, Injection Prevention وAudit Logs.",
    image: IMGS.code2,
  },
  {
    id: 110, category: "💻 برمجة",
    title: "Terraform Infrastructure-as-Code Guide",
    titleAr: "دليل Terraform للـ Infrastructure-as-Code",
    price: 125, pages: 362, rating: 4.7, downloads: 12800,
    desc: "Providers, Modules, State Management, Workspaces ونشر البنية التحتية على AWS وAzure.",
    image: IMGS.code3,
  },
  {
    id: 111, category: "💻 برمجة",
    title: "Machine Learning Algorithms – Visual Guide",
    titleAr: "خوارزميات تعلم الآلة – دليل مرئي",
    price: 140, pages: 428, rating: 4.8, downloads: 19200,
    badge: "BESTSELLER",
    desc: "شرح مرئي بصري لكل الخوارزميات الأساسية. متى تستخدم كل خوارزمية مع كود Python.",
    image: IMGS.ai,
  },
  {
    id: 112, category: "💻 برمجة",
    title: "Kubernetes Complete Deployment Guide",
    titleAr: "دليل Kubernetes الكامل للنشر",
    price: 145, pages: 416, rating: 4.7, downloads: 11600,
    desc: "Pods, Services, Deployments, Ingress, Helm Charts وإدارة الـ Clusters في الإنتاج.",
    image: IMGS.code,
  },
  {
    id: 113, category: "💻 برمجة",
    title: "Computer Science Interview Prep – 300 Questions",
    titleAr: "التحضير لمقابلات علم الحاسب – 300 سؤال",
    price: 150, pages: 542, rating: 4.9, downloads: 32800,
    badge: "HOT",
    desc: "300 سؤال وجواب شامل: OS, Networks, Databases, OOP, Design Patterns وـ System Design.",
    image: IMGS.code2,
  },
  {
    id: 114, category: "💻 برمجة",
    title: "Regular Expressions (Regex) – Complete Reference",
    titleAr: "دليل التعابير النمطية Regex الكامل",
    price: 75, pages: 198, rating: 4.7, downloads: 16400,
    desc: "من الأساسيات إلى Lookaheads والـ Named Groups. مع 100 Pattern جاهز للاستخدام.",
    image: IMGS.code3,
  },
  {
    id: 115, category: "💻 برمجة",
    title: "HTTP Protocol – Deep Dive for Developers",
    titleAr: "بروتوكول HTTP – شرح معمق للمطورين",
    price: 80, pages: 242, rating: 4.7, downloads: 13200,
    desc: "HTTP/1.1, HTTP/2, HTTP/3, Headers, Caching, CORS, Authentication وWebSockets.",
    image: IMGS.code,
  },
  {
    id: 116, category: "💻 برمجة",
    title: "Cybersecurity Checklists – 50 Checklists Pack",
    titleAr: "قوائم تدقيق الأمن السيبراني – 50 قائمة",
    price: 90, pages: 158, rating: 4.8, downloads: 14800,
    desc: "OWASP, Server Hardening, Code Review, Cloud Security وـ Incident Response Checklists.",
    image: IMGS.code2,
  },
  {
    id: 117, category: "💻 برمجة",
    title: "Open Source Licensing – Complete Guide",
    titleAr: "تراخيص المصدر المفتوح – الدليل الكامل",
    price: 55, pages: 148, rating: 4.6, downloads: 10200,
    desc: "MIT, Apache, GPL, LGPL, CC وتأثير كل رخصة على مشروعك التجاري. جدول مقارنة.",
    image: IMGS.code3,
  },
  {
    id: 118, category: "💻 برمجة",
    title: "DevOps Practices – Complete Handbook",
    titleAr: "ممارسات DevOps – الدليل الكامل",
    price: 135, pages: 398, rating: 4.8, downloads: 15600,
    badge: "NEW",
    desc: "Culture, Automation, Monitoring, IaC وـ SRE Principles. خارطة طريق للـ DevOps Engineer.",
    image: IMGS.code,
  },
  {
    id: 119, category: "💻 برمجة",
    title: "TypeScript Complete Developer Guide",
    titleAr: "دليل TypeScript الكامل للمطورين",
    price: 120, pages: 368, rating: 4.8, downloads: 21400,
    desc: "Types, Generics, Decorators, Utility Types وإعداد مشاريع Production-Ready بالكامل.",
    image: IMGS.code2,
  },
  {
    id: 120, category: "💻 برمجة",
    title: "Microservices Architecture – Design Guide",
    titleAr: "معمارية Microservices – دليل التصميم",
    price: 155, pages: 438, rating: 4.8, downloads: 13800,
    badge: "NEW",
    desc: "Service Decomposition, API Gateway, Event-Driven Design, Saga Pattern والـ Observability.",
    image: IMGS.code3,
  },

  // ─── 🎨 تصميم (10 products) ─────────────────────────────────────────
  {
    id: 121, category: "🎨 تصميم",
    title: "Graphic Design Principles – Complete PDF",
    titleAr: "مبادئ التصميم الجرافيكي – PDF كامل",
    price: 100, pages: 286, rating: 4.8, downloads: 19600,
    badge: "BESTSELLER",
    desc: "Balance, Contrast, Hierarchy, Color Theory, Typography وـ Grid Systems. مع أمثلة بصرية.",
    image: IMGS.design,
  },
  {
    id: 122, category: "🎨 تصميم",
    title: "Color Theory & Design – Visual Guide",
    titleAr: "نظرية الألوان والتصميم – دليل مرئي",
    price: 80, pages: 218, rating: 4.8, downloads: 22800,
    desc: "Color Psychology, Palettes, Modes, Contrast Ratios واستخدام الألوان في العلامات التجارية.",
    image: IMGS.design2,
  },
  {
    id: 123, category: "🎨 تصميم",
    title: "Typography Fundamentals – Complete Guide",
    titleAr: "أساسيات الطباعة – الدليل الكامل",
    price: 75, pages: 198, rating: 4.7, downloads: 16400,
    desc: "Kerning, Leading, Hierarchy، تصنيف الخطوط واختيار التايبوغرافي المثالي لكل سياق.",
    image: IMGS.design,
  },
  {
    id: 124, category: "🎨 تصميم",
    title: "The Complete Logo Design Guide",
    titleAr: "الدليل الكامل لتصميم الشعار",
    price: 90, pages: 254, rating: 4.8, downloads: 24600,
    badge: "HOT",
    desc: "أنواع الشعارات، مراحل التصميم، الأخطاء الشائعة وعرض الشعار على العميل باحتراف.",
    image: IMGS.design2,
  },
  {
    id: 125, category: "🎨 تصميم",
    title: "Figma Design Guide – Complete Reference",
    titleAr: "دليل Figma التصميمي الكامل",
    price: 110, pages: 312, rating: 4.9, downloads: 28400,
    badge: "BESTSELLER",
    desc: "Components, Auto Layout, Variables, Prototyping, Dev Mode وتسليم التصميم للمطورين.",
    image: IMGS.design,
  },
  {
    id: 126, category: "🎨 تصميم",
    title: "Branding Strategy Workbook",
    titleAr: "كتاب عمل استراتيجية العلامة التجارية",
    price: 95, pages: 178, rating: 4.7, downloads: 17200,
    desc: "تحديد هوية العلامة، القيم، Tone of Voice، الجمهور المستهدف وبناء القصة التسويقية.",
    image: IMGS.design2,
  },
  {
    id: 127, category: "🎨 تصميم",
    title: "Photoshop Complete Techniques Guide",
    titleAr: "دليل تقنيات Photoshop الكامل",
    price: 120, pages: 386, rating: 4.7, downloads: 20800,
    desc: "Masking, Retouching, Compositing, Smart Objects وتقنيات المحترفين مع 50 تمرين.",
    image: IMGS.design,
  },
  {
    id: 128, category: "🎨 تصميم",
    title: "UI Design Patterns – 100 Essential Patterns",
    titleAr: "أنماط تصميم UI – 100 نمط أساسي",
    price: 85, pages: 248, rating: 4.8, downloads: 21400,
    desc: "100 نمط تصميم مصنف: Navigation, Forms, Cards, Modals, Onboarding وـ Empty States.",
    image: IMGS.design2,
  },
  {
    id: 129, category: "🎨 تصميم",
    title: "Illustration Guide – Vector & Digital",
    titleAr: "دليل الرسوم التوضيحية – فيكتور ورقمي",
    price: 100, pages: 268, rating: 4.7, downloads: 15800,
    desc: "من الرسم اليدوي إلى الفيكتور الرقمي. Illustrator وProcreate لبناء أسلوب مميز.",
    image: IMGS.design,
  },
  {
    id: 130, category: "🎨 تصميم",
    title: "Video Editing Complete Guide – Premiere & DaVinci",
    titleAr: "دليل المونتاج الكامل – Premiere وDaVinci",
    price: 115, pages: 318, rating: 4.7, downloads: 18600,
    desc: "من الاستيراد إلى التصدير النهائي. Color Grading, Audio Mixing, Transitions وـ Effects.",
    image: IMGS.design2,
  },

  // ─── 💼 أعمال (10 products) ─────────────────────────────────────────
  {
    id: 131, category: "💼 أعمال",
    title: "The Negotiation Handbook – Win Every Deal",
    titleAr: "دليل التفاوض – اربح كل صفقة",
    price: 95, pages: 268, rating: 4.8, downloads: 19400,
    badge: "BESTSELLER",
    desc: "تقنيات BATNA, Anchoring, Mirroring وـ Labeling. مستمد من أبحاث Harvard على التفاوض.",
    image: IMGS.business,
  },
  {
    id: 132, category: "💼 أعمال",
    title: "Project Management Handbook – PMI Standard",
    titleAr: "دليل إدارة المشاريع – معيار PMI",
    price: 120, pages: 386, rating: 4.7, downloads: 16800,
    desc: "Waterfall, Agile, Hybrid. خطوات التخطيط، إدارة المخاطر، التواصل مع أصحاب المصلحة.",
    image: IMGS.business2,
  },
  {
    id: 133, category: "💼 أعمال",
    title: "The Agile & Scrum Complete Guide",
    titleAr: "دليل Agile وScrum الكامل",
    price: 100, pages: 312, rating: 4.8, downloads: 21200,
    badge: "HOT",
    desc: "Sprints, Retrospectives, User Stories, Definition of Done والأدوار في فريق Scrum.",
    image: IMGS.business,
  },
  {
    id: 134, category: "💼 أعمال",
    title: "Remote Work Productivity – Complete Guide",
    titleAr: "إنتاجية العمل عن بُعد – الدليل الكامل",
    price: 75, pages: 228, rating: 4.7, downloads: 24600,
    desc: "إدارة الوقت عن بُعد، التواصل الفعال، بناء ثقافة الفريق وأدوات العمل المشترك.",
    image: IMGS.business2,
  },
  {
    id: 135, category: "💼 أعمال",
    title: "Customer Service Excellence Handbook",
    titleAr: "دليل التميز في خدمة العملاء",
    price: 80, pages: 248, rating: 4.7, downloads: 14800,
    desc: "التعامل مع العملاء الصعبين، بناء الولاء، NPS, CSAT وبناء ثقافة التميز في الخدمة.",
    image: IMGS.business,
  },
  {
    id: 136, category: "💼 أعمال",
    title: "The Freelancer's Complete Business Guide",
    titleAr: "دليل الفريلانسر للأعمال الكامل",
    price: 90, pages: 286, rating: 4.8, downloads: 22800,
    badge: "BESTSELLER",
    desc: "تسعير خدماتك، العقود، إدارة العملاء، التسويق الذاتي والتخطيط المالي للمستقل.",
    image: IMGS.business2,
  },
  {
    id: 137, category: "💼 أعمال",
    title: "Tax Planning Guide – For Freelancers & SMEs",
    titleAr: "دليل التخطيط الضريبي – للمستقلين والمؤسسات",
    price: 85, pages: 218, rating: 4.6, downloads: 12600,
    desc: "الخصومات المسموحة، هيكلة الأعمال، التوثيق والتخطيط لتقليل الضريبة بشكل قانوني.",
    image: IMGS.finance,
  },
  {
    id: 138, category: "💼 أعمال",
    title: "Sales Funnel Mastery – Complete Guide",
    titleAr: "إتقان قمع المبيعات – الدليل الكامل",
    price: 110, pages: 312, rating: 4.7, downloads: 17400,
    desc: "TOFU, MOFU, BOFU. بناء قمع مبيعات يعمل على أتمتة، التتبع وزيادة معدلات التحويل.",
    image: IMGS.marketing,
  },
  {
    id: 139, category: "💼 أعمال",
    title: "Personal Finance Workbook – Full System",
    titleAr: "كتاب عمل المالية الشخصية – نظام كامل",
    price: 65, pages: 188, rating: 4.8, downloads: 26800,
    badge: "HOT",
    desc: "ميزانية 50/30/20، طريقة الظرف، صندوق الطوارئ والتخلص من الديون بخطة 12 شهراً.",
    image: IMGS.finance2,
  },
  {
    id: 140, category: "💼 أعمال",
    title: "Real Estate Investing – Complete Beginner Guide",
    titleAr: "الاستثمار العقاري – الدليل الكامل للمبتدئين",
    price: 120, pages: 338, rating: 4.7, downloads: 15400,
    desc: "أنواع الاستثمار العقاري، التحليل المالي للعقارات، التمويل وإدارة المحفظة.",
    image: IMGS.finance,
  },

  // ─── 🤖 ذكاء اصطناعي (10 products) ──────────────────────────────────
  {
    id: 141, category: "🤖 ذكاء اصطناعي",
    title: "ChatGPT Prompt Engineering Mastery",
    titleAr: "إتقان هندسة البرومبت – ChatGPT",
    price: 130, pages: 286, rating: 4.9, downloads: 38400,
    badge: "BESTSELLER",
    desc: "500+ برومبت جاهز لكل المجالات. Chain-of-Thought, Few-Shot وتقنيات الإخراج المتقدمة.",
    image: IMGS.ai,
  },
  {
    id: 142, category: "🤖 ذكاء اصطناعي",
    title: "LLM Fine-Tuning – Practical Guide",
    titleAr: "Fine-Tuning نماذج اللغة – دليل عملي",
    price: 200, pages: 398, rating: 4.8, downloads: 14800,
    desc: "LoRA, QLoRA, RLHF. كيف تدرب نموذجك الخاص على بياناتك. مع كود Python كامل.",
    image: IMGS.ai2,
  },
  {
    id: 143, category: "🤖 ذكاء اصطناعي",
    title: "AI Tools for Business – Complete Toolkit",
    titleAr: "أدوات الذكاء الاصطناعي للأعمال – دليل كامل",
    price: 110, pages: 268, rating: 4.8, downloads: 27600,
    badge: "HOT",
    desc: "أكثر من 150 أداة AI مصنفة لكل وظيفة: التسويق، البرمجة، التصميم، المبيعات والإدارة.",
    image: IMGS.ai,
  },
  {
    id: 144, category: "🤖 ذكاء اصطناعي",
    title: "Generative AI for Image – Complete Guide",
    titleAr: "الذكاء الاصطناعي التوليدي للصور",
    price: 120, pages: 298, rating: 4.8, downloads: 24200,
    desc: "Midjourney, DALL-E, Stable Diffusion. تقنيات البرومبت، الـ Styles وبناء سير عمل إبداعي.",
    image: IMGS.ai2,
  },
  {
    id: 145, category: "🤖 ذكاء اصطناعي",
    title: "Deep Learning Foundations – PDF Course",
    titleAr: "أسس التعلم العميق – كورس PDF",
    price: 180, pages: 486, rating: 4.8, downloads: 16400,
    badge: "NEW",
    desc: "Neural Networks, CNNs, RNNs, Transformers وـ Attention Mechanism. مع كود PyTorch.",
    image: IMGS.ai,
  },
  {
    id: 146, category: "🤖 ذكاء اصطناعي",
    title: "AI Ethics & Responsible AI – Guide",
    titleAr: "أخلاقيات الذكاء الاصطناعي – دليل",
    price: 90, pages: 218, rating: 4.7, downloads: 11800,
    desc: "Bias في النماذج، الشفافية، Privacy، التنظيم الحكومي وبناء أنظمة AI مسؤولة.",
    image: IMGS.ai2,
  },
  {
    id: 147, category: "🤖 ذكاء اصطناعي",
    title: "Natural Language Processing – Practical Guide",
    titleAr: "معالجة اللغة الطبيعية – دليل عملي",
    price: 160, pages: 428, rating: 4.8, downloads: 13600,
    badge: "NEW",
    desc: "Tokenization, Embeddings, Transformers, BERT, GPT. مع مشاريع Sentiment Analysis وNER.",
    image: IMGS.ai,
  },
  {
    id: 148, category: "🤖 ذكاء اصطناعي",
    title: "AI for Marketing – Complete Playbook",
    titleAr: "الذكاء الاصطناعي للتسويق – الدليل الكامل",
    price: 140, pages: 318, rating: 4.8, downloads: 21400,
    desc: "Personalization، إنشاء المحتوى، تحليل البيانات والتوقع التسويقي بالـ AI.",
    image: IMGS.ai2,
  },
  {
    id: 149, category: "🤖 ذكاء اصطناعي",
    title: "Computer Vision – From Theory to Practice",
    titleAr: "رؤية الحاسب – من النظرية إلى التطبيق",
    price: 170, pages: 446, rating: 4.7, downloads: 11200,
    desc: "Object Detection, Segmentation, YOLO, OpenCV. مع مشاريع Facial Recognition وـ OCR.",
    image: IMGS.ai,
  },
  {
    id: 150, category: "🤖 ذكاء اصطناعي",
    title: "Building AI Agents – LangChain & AutoGPT",
    titleAr: "بناء وكلاء AI – LangChain وAutoGPT",
    price: 190, pages: 368, rating: 4.9, downloads: 19800,
    badge: "NEW",
    desc: "RAG, Tool Use, Memory, Multi-Agent Systems. بناء وكلاء ذكاء اصطناعي من الصفر.",
    image: IMGS.ai2,
  },
];
